In [ ]:
#pip install ipykernel torch

In [2]:
import torch
torch.__version__

/home/deb/Coding/Pytorch/.venv/lib/python3.8/site-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: numpy.core.multiarray failed to import (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


'2.4.1+cu121'

## Section 1
1. Creating Tensors
2. Data Types
3. Tensor Maths
4. Working with NumPy

In [3]:
# Empty 2 by 2 array
# Tensor is a Multidimensional array starting with empty array 
e = torch.empty(2, 2)
e

tensor([[1.3235e-14, 1.1708e-19],
        [1.3563e-19, 5.0746e+31]])

In [4]:
# empty does not create random values exactly
r = torch.rand(2, 2)
r

tensor([[0.8479, 0.5201],
        [0.9318, 0.8301]])

In [5]:
z = torch.zeros(2, 2)
z

tensor([[0., 0.],
        [0., 0.]])

In [6]:
# Fill 2 x 2 array with the value 3
c = torch.full((2, 2), 3)
c

tensor([[3, 3],
        [3, 3]])

In [7]:
l = torch.tensor([[1, 2], [3, 4]])
l

tensor([[1, 2],
        [3, 4]])

In [10]:
import numpy as np
n = np.linspace(0, 5, 5)
n

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [11]:
nt = torch.tensor(n)
nt
# numpy array converted to tensor

tensor([0.0000, 1.2500, 2.5000, 3.7500, 5.0000])

In [16]:
print(nt[1:])
print(nt[0])

tensor([1.2500, 2.5000, 3.7500, 5.0000])
tensor(0.)


In [18]:
s = torch.ones(3, 3, dtype=torch.float)
s

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [19]:
identity_matrix = torch.eye(3, 3)

identity_matrix + torch.zeros(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
identity_matrix - torch.ones(3, 3)

tensor([[ 0., -1., -1.],
        [-1.,  0., -1.],
        [-1., -1.,  0.]])

In [21]:
identity_matrix * 3

tensor([[3., 0., 0.],
        [0., 3., 0.],
        [0., 0., 3.]])

In [22]:
# Element wise tensor multiplication
identity_matrix * torch.full((3, 3), 4)

tensor([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]])

In [23]:
# Dot product - @
x = torch.rand(3, 4)
y = torch.rand(4, 3)

x @ y

tensor([[0.9707, 1.1411, 1.4429],
        [0.8798, 0.9235, 0.8839],
        [0.7760, 0.9699, 1.1735]])

In [ ]:
# Handy ML component operations
# like getting the index of the maximum value